// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadUndoFileRestoreResponse = {
/**
 * Null when the thread has no restore to undo, which callers should
 * report rather than treat as success.
 */
summary: string | null, };
