// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadUndoFileRestoreResponse = {
/**
 * Null when the thread has no restore to undo, which callers should
 * report rather than treat as success.
 */
summary: string | null,
/**
 * Rollout file holding the conversation as it stood before the rewind,
 * written out so the caller can fork from it (`thread/fork.path`).
 *
 * The copy is taken at rewind time and kept by the snapshot store, so it
 * does not depend on the superseded thread still existing or still being
 * where it was. Null when the rewind predates conversation capture or the
 * copy could not be written; the file restore above still stands.
 */
conversationPath: string | null, };
