// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Undo this thread's most recent `restoreFiles` rewind by returning the
 * workspace to the safety checkpoint taken just before it.
 */
export type ThreadUndoFileRestoreParams = { threadId: string, };
