// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRestoreFilesToTurnResponse = {
/**
 * Null when the thread is not tracking snapshots or the turn has none,
 * which callers should report rather than treat as success.
 */
summary: string | null, };
